# Generated by Django 5.1.6 on 2025-06-26 04:47

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('inventory', '0003_inventoryflow_invoice'),
    ]

    operations = [
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('oic', models.CharField(blank=True, help_text='Ordem Interna de Compra ou identificador similar.', max_length=100, null=True, verbose_name='OIC')),
                ('quantity', models.PositiveIntegerField(verbose_name='Quantidade')),
                ('request_date', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Data do Pedido')),
                ('is_billed', models.BooleanField(default=False, verbose_name='Cobrado')),
                ('billed_date', models.DateTimeField(blank=True, help_text='Preenchido apenas quando o serviço é marcado como cobrado.', null=True, verbose_name='Data da Cobrança')),
                ('email', models.EmailField(blank=True, max_length=254, null=True, verbose_name='Email do Pedido')),
                ('notes', models.TextField(blank=True, null=True, verbose_name='Observações')),
                ('bag_type', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='inventory.bagtype', verbose_name='Tipo de Saco')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='inventory.company', verbose_name='Empresa')),
                ('weight', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='inventory.weight', verbose_name='Peso (Kg)')),
            ],
            options={
                'verbose_name': 'Serviço',
                'verbose_name_plural': 'Serviços',
                'ordering': ['-request_date'],
            },
        ),
    ]
