# Generated by Django 5.1.6 on 2025-07-02 20:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='service',
            name='email',
            field=models.TextField(blank=True, max_length=254, null=True, verbose_name='Email do Pedido'),
        ),
    ]
