# Generated by Django 5.1.6 on 2025-07-02 20:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0002_alter_service_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='service',
            name='billed_date',
            field=models.DateField(blank=True, help_text='Preenchido apenas quando o serviço é marcado como cobrado.', null=True, verbose_name='Data da Cobrança'),
        ),
    ]
