# Generated by Django 5.1.6 on 2025-02-15 00:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Empresa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('oic', models.IntegerField()),
                ('imagem', models.ImageField(blank=True, null=True, upload_to='uploads/')),
                ('tipo', models.CharField(choices=[('Juta', 'Juta'), ('Poli', 'Poli'), ('Papel', 'Papel')], max_length=10)),
                ('kg', models.IntegerField(choices=[(30, '30kg'), (60, '60kg')])),
                ('quantidade', models.IntegerField()),
                ('pago', models.BooleanField(default=False)),
                ('link_email', models.CharField(blank=True, max_length=255, null=True)),
                ('data', models.DateField(auto_now=True)),
                ('empresa', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='inventory.empresa')),
            ],
        ),
    ]
