# Generated by Django 5.1.6 on 2025-02-20 03:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='BagType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Weight',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=10, unique=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='item',
            name='empresa',
        ),
        migrations.CreateModel(
            name='TotalStock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField(default=0)),
                ('bag_type', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='inventory.bagtype')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='inventory.company')),
                ('weight', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='inventory.weight')),
            ],
            options={
                'unique_together': {('company', 'weight', 'bag_type')},
            },
        ),
        migrations.CreateModel(
            name='InventoryFlow',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField()),
                ('movement_date', models.DateTimeField(auto_now_add=True)),
                ('bag_type', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='inventory.bagtype')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='inventory.company')),
                ('weight', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='inventory.weight')),
            ],
        ),
        migrations.DeleteModel(
            name='Empresa',
        ),
        migrations.DeleteModel(
            name='Item',
        ),
    ]
