# Generated by Django 5.1.6 on 2025-06-25 13:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0002_bagtype_company_weight_remove_item_empresa_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='inventoryflow',
            name='invoice',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
